version: '3.8'

services:
  # Node.js service
  app:
    build:
      context: .  # Build from the current directory (where Dockerfile is)
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5433/mydatabase  # Set environment variables
      - NODE_ENV=production
    depends_on:
      - db

  # PostgreSQL service
  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"  # Map host port 4003 to container port 4003
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  consul-client:
    image: hashicorp/consul
    restart: always
    network_mode: host
    volumes:
     - ./consul/client.json:/consul/config/client.json
     - ./certs/:/consul/config/certs/
     - ./tokens/:/consul/config/tokens/
    command: "agent"

volumes:
  postgres_data:

